# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desing_minimal.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(358, 391)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setToolTipDuration(0)
        MainWindow.setStyleSheet("QMainWindow {\n"
"}\n"
"\n"
"QWidget {\n"
"/* цвета #fafafa; ededed;  */\n"
"background: #ededed;\n"
"font-family: Avantgarde, TeX Gyre Adventor, URW Gothic L, sans-serif\n"
"/* color: #ab9d00;   */\n"
"}\n"
".QLineEdit::hover{\n"
"background-color: #3d3d3d;\n"
"}\n"
"QLineEdit {\n"
"color : #f0f0f0;\n"
"padding: 0 10px 0 10px;\n"
"font-size: 18px;\n"
"background: #4f4f4f;\n"
"border: 0.1px solid #ebebeb;\n"
"border-radius: 10px;\n"
"/* color: #474747;  */\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: black;\n"
"/* font-family: Ubuntu, verdana, sans-serif; */\n"
"border: 1px #ebebeb;\n"
"border-radius: 20px;\n"
"background-color: #1c1c1c;\n"
"color: white;\n"
"position: relative;\n"
"padding: 5px;\n"
"font-weight: bold; \n"
"}\n"
"\n"
".QPushButton:hover{\n"
"background-color: #2e2e2e;\n"
"}\n"
"\n"
"QStatusBar{\n"
"font-family: FreeMono;\n"
"font-size: 12px;\n"
"}")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 300, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 230, 321, 51))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 160, 321, 51))
        font = QtGui.QFont()
        font.setFamily("Avantgarde,TeX Gyre Adventor,URW Gothic L,sans-serif")
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 20, 91, 111))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap(":/image/89.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 358, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("FreeMono")
        font.setBold(False)
        font.setWeight(50)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RDP over SSH Client"))
        self.pushButton.setText(_translate("MainWindow", "Подключить"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Пароль"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Логин"))
        self.action.setText(_translate("MainWindow", "О программе"))
        self.action_2.setText(_translate("MainWindow", "Помощь"))
